#!/bin/bash
# @Function
# convert to Absolute Path.
#
# @Usage
#   # print Absolute Path of current directory.
#   $ ./ap
#   # print Absolute Path of arguments. readlink -f 
#   $ ./ap a.txt ../dir1/b.txt
#
# @author StrongIt

[ $# -eq 0 ] && files=(.) || files=("$@")

for f in "${files[@]}" ; do
    ! [ -e "$f" ] && {
        echo "$f does not exists!"
        continue
    }
    dirname $(readlink -f "$f")
done
